name: Deploy Heroku
on:
  push:
    paths:
      - '**.ts'
      - '**.json'
      - 'test/**'
      - 'src/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petbook-back-dev"
          heroku_email: "jbelevicius@kayak.com"
